### ISSUE TITLE
Question about Ansible

### ISSUE THREAD

**Issue by janban-outlook** [h8pewou/homelab#1]
Hi Adam
I was looking at your homelab diagram. Impressive.
I have a question: what do you use Ansible for? Is that the first VM you set up, and from there using playbooks to spin up the rest of the virtual machines?
I am considering to first install AWX on a Debian machine, and then use that to build up the entire network, including setting up Proxmox. What do you think?

**Comment by h8pewou** [comment]
Hello Jan! Thank you very much! I have setup pretty much all the VMs manually before I bumped into AWX. Doing it the way you described it would be a lot more elegant. My ansible setup is an afterthought and I am yet to find a really good use case for it. With that said, I am planning to automate the configuration management of the telegraf agents with it at some point. 

I have also added Omada SDN components and a third cluster node since the last update, I will update the documentation when it is fully configured. :)

**Comment by polachz** [comment]
Sorry for bumping this way... But I have a question about glusterFs performance and SSD wearness... 

For many reasons I can't use SFP cards. I do not plan any  much data consuming implementatkons in my lab, but i have found many different opinions about glusterFS speed and performence, especally on 1GBit lines. In my old hardware planned for servrs i have only 2x 1Gbit cards...

can you share with me your experience from your lab functionality? 

Thank you so much

**Comment by h8pewou** [comment]
Hello @polachz! 

SSD wear never caused any operational issues on my gluster volume. With that said, my consumer grade SSDs started to show their age after 3-4 years of use.

1Gbit may work with a very light use case, but it will be a serious bottleneck if you add more than a few VMs. My 2.5GBit USB adapters worked surprisingly well, consistently pushing data around 1.8-2Gbits, with occasional peaks around the advertised speed. Bonding two gigabit links may also help, but it never worked well on my setup. I have used the additional 1Gbit links to facilitate cluster and VM traffic instead. This was my sweetspot:

- 2.5 Gbit link dedicated to gluster storage.
- 1 Gbit intel nic dedicated to VM traffic.
- 1 Gbit realtek nic dedicated to PVE and other management traffic.

I hope this helps. :)

**Comment by h8pewou** [comment]
I'm also closing this issue, as Ansible never became a core part of this setup.
